version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'â¬†ï¸ğŸŸ¢'
      prefix-development: 'â¬†ï¸ğŸŸ¡'
    assignees:
      - yo
    reviewers:
      - yo
    open-pull-requests-limit: 200
    rebase-strategy: auto
